### ISSUE TITLE
Advanced compiler settings missing for Compass?

### ISSUE THREAD

**Issue by rpkoller** [bdkjones/CodeKit2#17]
In 1.x you had the option to let an external version of Compass compile your scss:

![compass](https://f.cloud.github.com/assets/1665422/1772961/d974a5ec-67dc-11e3-9e3c-34982dbe7857.png)

Is the option gone in 2.0? Or how do you accomplish to use gems like Toolkit, Modular Scale or Singularity?

I tried with more or less out of the box settings, but i get an error like that:  

```
/Applications/CodeKit 2.app/Contents/Resources/engines/compass/bin/../lib/compass/watcher/project_watcher.rb:1:in `require': no such file to load -- listen (LoadError)
    from /Applications/CodeKit 2.app/Contents/Resources/engines/compass/bin/../lib/compass/watcher/project_watcher.rb:1
    from /Applications/CodeKit 2.app/Contents/Resources/engines/compass/bin/../lib/compass/watcher.rb:3:in `require'
    from /Applications/CodeKit 2.app/Contents/Resources/engines/compass/bin/../lib/compass/watcher.rb:3
    from /Applications/CodeKit 2.app/Contents/Resources/engines/compass/bin/../lib/compass.rb:33:in `require'
    from /Applications/CodeKit 2.app/Contents/Resources/engines/compass/bin/../lib/compass.rb:33
    from /Applications/CodeKit 2.app/Contents/Resources/engines/compass/bin/../lib/compass.rb:32:in `each'
    from /Applications/CodeKit 2.app/Contents/Resources/engines/compass/bin/../lib/compass.rb:32
    from /Applications/CodeKit 2.app/Contents/Resources/engines/compass/bin/compass:32:in `require'
    from /Applications/CodeKit 2.app/Contents/Resources/engines/compass/bin/compass:32
    from /Applications/CodeKit 2.app/Contents/Resources/engines/compass/bin/compass:20:in `fallback_load_path'
    from /Applications/CodeKit 2.app/Contents/Resources/engines/compass/bin/compass:31
```

**Comment by mgrn0** [comment]
I get the exact same error, but allready when trying to create a new compass project.

**Comment by bramdevries** [comment]
CodeKit -> Preferences -> Compilers -> Other Tools - Compass. That's where you can set a different executable.

**Comment by rpkoller** [comment]
Uh since in the video Bryan told that most of the configuration was moved to the default and project preferences i haven't really looked there. My bad. Cool works perfectly now. Thanks Bram!
