### ISSUE TITLE
Problems with Jade Mixin

### ISSUE THREAD

**Issue by jonnitto** [bdkjones/CodeKit2#249]
I use Jade to design the prototypes. I defined some mixins to speed up the whole progress. In Codekit 1, I've got no problems the compile the jade but in Codekit 2 I got always the following error:

```
/Applications/CodeKit.app/Contents/Resources/engines/jade/lib/runtime.js:202
  throw err;
        ^
Error: /Users/jon/carIT/GitHub/Interface/Codekit/assets/jade/_elemente/mixin.jade:23
    21|                             label
    22|                                 input(type=type, name=attributes.id, attributes)
  > 23|                                 |
    24|                                 =label
    25|             else if type == "textarea"
    26|                 .form-group

unexpected text |

    at Object.Lexer.fail (/Applications/CodeKit.app/Contents/Resources/engines/jade/lib/lexer.js:804:11)
    at Object.Lexer.next (/Applications/CodeKit.app/Contents/Resources/engines/jade/lib/lexer.js:863:15)
    at Object.Lexer.lookahead (/Applications/CodeKit.app/Contents/Resources/engines/jade/lib/lexer.js:113:46)
    at Parser.lookahead (/Applications/CodeKit.app/Contents/Resources/engines/jade/lib/parser.js:111:23)
    at Parser.peek (/Applications/CodeKit.app/Contents/Resources/engines/jade/lib/parser.js:88:17)
    at Parser.tag (/Applications/CodeKit.app/Contents/Resources/engines/jade/lib/parser.js:768:30)
    at Parser.parseTag (/Applications/CodeKit.app/Contents/Resources/engines/jade/lib/parser.js:690:17)
    at Parser.parseExpr (/Applications/CodeKit.app/Contents/Resources/engines/jade/lib/parser.js:199:21)
    at Parser.block (/Applications/CodeKit.app/Contents/Resources/engines/jade/lib/parser.js:660:25)
    at Parser.tag (/Applications/CodeKit.app/Contents/Resources/engines/jade/lib/parser.js:777:26)
```

This is my jade mixin (a part of it):

```
mixin form-group(label, style)
    - type = attributes.type || "text"
    - labelClass = "control-label"
    if type != "checkbox" && type != "radio"
        - attributes.placeholder = attributes.placeholder || label
    if type == "textarea"
        - attributes.rows = attributes.rows || 3
    if style == "inline"
        - labelClass = "sr-only"
    case  style
        when "horizontal"
            if type == "checkbox" || type == "radio"
                .form-group
                    .col-lg-offset-3.col-lg-9
                        div(class=type)
                            label
                                input(type=type, name=attributes.id, attributes)
                                |  
                                =label
            else if type == "textarea"
                .form-group
                    label.control-label.col-lg-3(for=attributes.id)= label
                    .col-lg-9
                        textarea.form-control(name=attributes.id, attributes)
            else if type == "static"
                .form-group
                    label.control-label.col-lg-3= label
                    .col-lg-9
                        p.form-control-static= attributes.value
            else
                .form-group
                    label.control-label.col-lg-3(for=attributes.id)= label
                    .col-lg-9
                        input(type=type, name=attributes.id,  attributes).form-control
        default
            if type == "checkbox" || type == "radio"
                if style == "inline"
                    label(class="#{type}-inline")
                        input(type=type, name=attributes.id,  attributes)
                        |  
                        =label
                else
                    div(class=type)
                        label
                            input(type=type, name=attributes.id,  attributes)
                            |  
                            =label
            else if type == "textarea"
                .form-group
                    label(class=labelClass, for=attributes.id)= label
                    textarea.form-control(name=attributes.id, attributes)
            else if type == "static"
                .form-group
                    label(class=labelClass)= label
                    p.form-control-static= attributes.value
            else
                .form-group
                    label(class=labelClass, for=attributes.id)= label
                    input(type=type, name=attributes.id,  attributes).form-control
mixin button(tag,style)
    - style = style || "default"
    - tag = tag || "button"
    if tag == "a"
        a(class="btn btn-#{style}", href="#", attributes)
            block
    else
        button(class="btn btn-#{style}", type=tag, attributes)
            block
```

and this is in the jade file:

```
form.validate
    +form-group('Name')#name(required)
    +button('submit') Send
```

**Comment by bdkjones** [comment]
CodeKit 2 has a newer version of Jade. Please make sure your file has the correct syntax for that version. Try compiling it on the command line with the latest jade release. If that works correctly, post the file here so I can test.

**Comment by bdkjones** [comment]
Need some feedback on this, or I'm going to close.
