### ISSUE TITLE
Cannot compile .styl

### ISSUE THREAD

**Issue by Andreyco** [bdkjones/CodeKit2#264]
After upgrading to Beta 17 (replacing it in Application folder) I get this when trying to compile Stylus file

```
module.js:340
    throw err;
          ^
Error: Cannot find module '/Applications/CodeKit.app/Contents/Resources/engines/package.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Applications/CodeKit.app/Contents/Resources/engines/nib/nib.js:35:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

Content of `.styl` file is as simple as this

```
@import 'nib'

.cf
.clear
.clearfix
    clearfix()
```

I think, it is related to NIB

**Comment by bdkjones** [comment]
Fixed for Beta 18. Thanks.

**Comment by Andreyco** [comment]
I can confirm this, works like a charm. Thank you! :)
