### ISSUE TITLE
Stylus needs extra arguments to find Bower components

### ISSUE THREAD

**Issue by phyllisstein** [bdkjones/CodeKit2#285]
I just tried to add a component called [Jeet](http://jeet.gs) to a project that's using Stylus, but found that CodeKit's Stylus compiler didn't know where to look for it. I can make it work on the command line by adding `--include ./bower_components/jeet` to the `stylus` command, but CodeKit throws the following error:

```
/Applications/CodeKit.app/Contents/Resources/engines/stylus/bin/stylus:540
              throw err;
                    ^
Error: /Users/danielsh/Documents/CLMP/Tech/Static Demo/stylus/index.styl:20
   16| 1.443     0.09    0.09      11.100
   17| **********************************/
   18| 
   19| @import 'nib'
 > 20| @import 'jeet'
   21| 
   22| font-stack = adobe-caslon-pro, Garamond, Times, serif
   23| 

failed to locate @import file jeet.styl

    at Evaluator.visitImport (/Applications/CodeKit.app/Contents/Resources/engines/stylus/lib/visitor/evaluator.js:882:21)
    at Evaluator.Visitor.visit (/Applications/CodeKit.app/Contents/Resources/engines/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/Applications/CodeKit.app/Contents/Resources/engines/stylus/lib/visitor/evaluator.js:159:18)
    at Evaluator.visitRoot (/Applications/CodeKit.app/Contents/Resources/engines/stylus/lib/visitor/evaluator.js:713:27)
    at Evaluator.Visitor.visit (/Applications/CodeKit.app/Contents/Resources/engines/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/Applications/CodeKit.app/Contents/Resources/engines/stylus/lib/visitor/evaluator.js:159:18)
    at Evaluator.evaluate (/Applications/CodeKit.app/Contents/Resources/engines/stylus/lib/visitor/evaluator.js:234:15)
    at Renderer.render (/Applications/CodeKit.app/Contents/Resources/engines/stylus/lib/renderer.js:80:26)
    at /Applications/CodeKit.app/Contents/Resources/engines/stylus/bin/stylus:534:15
    at fs.js:266:14
```

**Comment by bdkjones** [comment]
Yea, there are roughly 4,567,213 different libraries out there for Less, Sass and Stylus.

There's no way CodeKit can know about all of them. In this case, you should change your `@import` statement to use a relative path to the folder where `jeet.styl` is located.

This is the same way you would have to add `bower_components/jquery/jquery.js` to the `src=` attribute of a script tag in HTML.

It's far cleaner to do that in your code than it is for me to add some text field somewhere buried in CodeKit where you can specify a list of additional include paths to pass to each of the compilers.

**Comment by phyllisstein** [comment]
Gotcha! I don't disagree, I just wasn't certain whether I was breaking the magic again. Thanks for the tip!
